### ISSUE TITLE
_happened? is awkward, 

### ISSUE THREAD

**Issue by robotdana** [joshmcarthur/disclosure#1]
I like this project :) 

I suggest using the present verb, rather than the past verb because it should happen just at the time the action happens, so a past verb is confusing (we want to know it is closing, not that it has been closed)

so: `[:close, :create, :join, :follow, :friend]` (because friend is a verb now)

and the taggy bit could be something along the lines of `react_to_close?` or `needs_join_notification?`

or even, `disclose_create?` if you want to be all branded and stuff.

**Comment by joshmcarthur** [comment]
@dnl I like `react_to_*?`. The names of the actions don't really matter to the library, it's action-name-agnostic. Would you like to make this patch? You'll need to change:
- https://github.com/joshmcarthur/disclosure/blob/master/lib/disclosure.rb#L30
- https://github.com/joshmcarthur/disclosure/blob/master/lib/disclosure.rb#L49
- https://github.com/joshmcarthur/disclosure/blob/master/spec/disclosure_spec.rb#L103
